[project]
name = "git-sandbox-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Manjunadh Kandavalli", email = "manjunadhkandavalli@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.142.2",
    "pydantic>=2.13.5",
    "uvicorn>=0.54.0",
]

[project.scripts]
git-sandbox-app = "git_sandbox_app:main"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"
